[package]
name = "kernelraspberrypi"
version = "0.1.0"
edition = "2021"
license = "MIT"
description ="kernel development"
repository ="https://github.com/girishnarayan/kernelraspberrypi.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
